name: quizcopa
description: Projeto flutter de um Quiz sobre a copa do mundo, para prática de trabalho com respostas e pontuações.
publish_to: 'Priscila Guimarães' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-374.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/

  fonts:
     - family: FjallaOne
       fonts:
         - asset: fonts/FjallaOne-Regular.ttf

